version: '3.7'

services:
  db:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 8001:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./themes/:/var/www/html/wp-content/themes/
      - ./uploads/:/var/www/html/wp-content/uploads/

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8002:8080
    restart: always
    environment:
      DATABASE_URL: mysql://wordpress:wordpress@db:3306/wordpress
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data: {}
